name = "cf-imgbed"
compatibility_date = "2025-08-10"

[assets]
directory = "./"

exclude = [
  "node_modules/**/*",
  "*.log",
  "*.md",
  "*.toml",
  "package*.json",
  "tsconfig*.json",
  "wrangler*.toml"
]
